const jCategory = [
  {
    index: 0,
    image: "../images/google-logo.webp",
    title: "Web Developer",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Google",
    location: "Kathmandu, Nepal",
    vacancy: "01",
    hours: "50h / W",
    description:
      "Web Developer at Google — responsible for designing, developing, and maintaining dynamic, user-friendly, and responsive web applications that deliver exceptional user experiences. The role involves working closely with designers, product managers, and backend engineers to build and optimize web interfaces using modern technologies such as HTML, CSS, JavaScript, and React. You will ensure website performance, accessibility, and cross-browser compatibility while implementing best practices in coding and UI/UX design. This position requires strong problem-solving skills, attention to detail, and a passion for creating efficient and visually appealing web solutions that align with Google’s high standards of quality and innovation.",
    workplace: "Work from home",
    education: "Bachelor degree in any Computer Science Course",
    experience: "2 to 5 years",
  },
  {
    index: 1,
    image: "../images/instagram-logo.webp",
    title: "Freelancer",
    rate: "$600-1000/m",
    av: "Freelancer",
    companyName: "Instagram",
    location: "Remote",
    vacancy: "02",
    hours: "30h / W",
    description:
      "Freelancer at Instagram — responsible for creating engaging social media content, managing brand collaborations, and supporting digital campaigns. The role includes working with the marketing team to design and deliver creative solutions for online engagement. Ideal for self-motivated individuals with strong communication and content creation skills.",
    workplace: "Remote",
    education: "Bachelor degree in Marketing or related field",
    experience: "1 to 3 years",
  },
  {
    index: 2,
    image: "../images/apple-logo.webp",
    title: "Business Associate",
    rate: "$1100-1500/m",
    av: "Part Time",
    companyName: "Apple",
    location: "California, USA",
    vacancy: "01",
    hours: "45h / W",
    description:
      "Business Associate at Apple — responsible for supporting business development initiatives, analyzing market trends, and managing client relationships. The position requires a strategic mindset, data analysis skills, and the ability to work cross-functionally with sales and product teams to drive growth and efficiency.",
    workplace: "On-site",
    education: "Bachelor degree in Business Administration or related field",
    experience: "3 to 6 years",
  },
  {
    index: 3,
    image: "../images/linkedin-logo.webp",
    title: "Digital Marketing",
    rate: "$800-1200/m",
    av: "Full Time",
    companyName: "LinkedIn",
    location: "Singapore",
    vacancy: "03",
    hours: "40h / W",
    description:
      "Digital Marketing Specialist at LinkedIn — responsible for planning and executing digital marketing campaigns, managing SEO/SEM strategies, and analyzing engagement metrics. The role involves enhancing brand visibility and improving lead generation through creative digital strategies.",
    workplace: "Hybrid",
    education: "Bachelor degree in Marketing, Communication, or related field",
    experience: "2 to 4 years",
  },
  {
    index: 4,
    image: "../images/facebook-logo.webp",
    title: "User Experience",
    rate: "$950-1300/m",
    av: "Part Time",
    companyName: "Facebook",
    location: "Canada",
    vacancy: "02",
    hours: "40h / W",
    description:
      "User Experience Designer at Facebook — responsible for crafting intuitive and engaging user interfaces, conducting usability testing, and collaborating with cross-functional teams to improve product experiences. The position demands creativity, empathy for users, and proficiency with design tools such as Figma or Adobe XD.",
    workplace: "Hybrid",
    education: "Bachelor degree in Design, HCI, or related field",
    experience: "2 to 5 years",
  },
];
